# Generated by Django 6.0.2 on 2026-03-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatars/A47.png', 'A47'), ('avatars/Fighter 1.png', 'Fighter 1'), ('avatars/Fighter 2.png', 'Fighter 2'), ('avatars/Fighter 3.png', 'Fighter 3'), ('avatars/Fighter 4.png', 'Fighter 4')], default='avatars/A47.png', max_length=64),
        ),
    ]
