# Generated by Django 5.2.12 on 2026-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_profile_github_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='images/avatar-default.svg', max_length=64),
        ),
    ]
