# Generated by Django 5.2.12 on 2026-05-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
